api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

circuit:
    resource: "@CircuitBundle/Controller/"
    type:     annotation
    prefix:   /

element:
    resource: "@ElementBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"